---
- name: Prepare Alpine container
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Python 3 and OpenRC
      ansible.builtin.raw: apk add --no-cache python3 openrc
      changed_when: true

    - name: Ensure /etc/apk/repositories exists
      ansible.builtin.raw: test -f /etc/apk/repositories || echo "" > /etc/apk/repositories
      changed_when: true
